### ISSUE TITLE
Pull method accepts options array, but doesn't use it in request

### ISSUE THREAD

**Issue by IhorHolovatsky** [lucit-cc/lucit-layout-drive-api#1]
`GetItem` method contains following call:

```
 $result = $this->pull($id,[
            "location_id" => $locationId
        ]);
```

So we are passing location_id options, but `pull` method doesn't insert these options to query string.
It this expected?

https://github.com/lucit-cc/lucit-layout-drive-api/blob/3daf025eb048aa85317a5132442f8e02130b113a/src/Lucit/LucitDrive.php#L53

**Comment by ericlucit** [comment]
Closed by da9d4d964951ea0bc0f2e4e7522069ce5d254f7f
